# Generated by Django 3.1.4 on 2020-12-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201221_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_sell',
            field=models.IntegerField(default=0),
        ),
    ]
