# Generated by Django 3.1.3 on 2020-12-20 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201214_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
