# Generated by Django 3.1.4 on 2021-01-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210110_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='amount_sell',
            field=models.IntegerField(default=0),
        ),
    ]
