# Generated by Django 3.1.4 on 2021-01-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_sizeproduct_amount_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
