# Generated by Django 3.1.4 on 2020-12-23 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_auto_20201223_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 16, 7, 30, 382955)),
        ),
    ]
