# Generated by Django 3.1.4 on 2020-12-28 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20201223_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 16, 14, 36, 515000)),
        ),
    ]
