# Generated by Django 3.1.4 on 2020-12-30 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_auto_20201228_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 14, 15, 36, 282493)),
        ),
    ]
