# Generated by Django 3.1.3 on 2020-12-20 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_auto_20201220_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 16, 49, 50, 141663)),
        ),
    ]
