# Generated by Django 3.1.4 on 2021-01-02 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_auto_20201230_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 20, 30, 13, 62606)),
        ),
    ]
