# Generated by Django 3.1.4 on 2021-01-03 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_auto_20210102_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 10, 7, 56, 465799)),
        ),
    ]
