# Generated by Django 3.1.4 on 2021-01-10 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_auto_20210110_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 17, 17, 24, 144807)),
        ),
    ]
