# Generated by Django 3.1.4 on 2021-01-10 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_sizeproduct_amount_sell'),
        ('purchase', '0022_auto_20210110_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sizeproduct'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 17, 25, 37, 61800)),
        ),
    ]
