# Generated by Django 3.1.4 on 2021-01-10 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_auto_20210110_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproduct',
            old_name='product',
            new_name='sizeProduct',
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 18, 15, 5, 822820)),
        ),
    ]
