# Generated by Django 3.1.4 on 2021-01-10 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_auto_20210110_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 18, 44, 55, 176896)),
        ),
    ]
