# Generated by Django 3.1.4 on 2021-01-11 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0025_auto_20210110_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 9, 30, 22, 16872)),
        ),
    ]
