# Generated by Django 3.1.4 on 2021-01-11 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0027_auto_20210111_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 16, 47, 8, 84792)),
        ),
    ]
