# Generated by Django 3.1.3 on 2021-01-12 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0029_auto_20210111_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 13, 59, 51, 238007)),
        ),
    ]
