# Generated by Django 3.1.3 on 2021-01-12 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0030_auto_20210112_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 15, 0, 38, 263641)),
        ),
    ]
