# Generated by Django 3.1.4 on 2021-01-12 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0031_auto_20210112_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 15, 19, 52, 670372)),
        ),
    ]
