# Generated by Django 3.1.4 on 2021-01-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210110_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='sizeProduct',
        ),
    ]
