# Generated by Django 3.1.4 on 2020-12-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.TextField(default='', max_length=50)),
                ('district', models.TextField(default='', max_length=50)),
                ('wards', models.TextField(default='', max_length=50)),
                ('address', models.TextField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
