# Generated by Django 3.1.4 on 2020-12-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='permManager',
            field=models.BooleanField(default=False),
        ),
    ]
