# Generated by Django 3.1.4 on 2020-12-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_address_permmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='permManager',
        ),
    ]
