# Generated by Django 3.1.4 on 2021-01-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
