# Generated by Django 3.1.4 on 2020-12-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='fistName',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='lastName',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='wards',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
