# Generated by Django 3.1.4 on 2021-01-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201223_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fistName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
