# Generated by Django 3.1.3 on 2021-01-12 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20210102_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='shippingEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Đã tiếp nhận'), ('2', 'Đang chuẩn bị'), ('3', 'Đang giao hàng'), ('4', 'Đã giao hàng'), ('5', 'Đã hủy'), ('6', 'Tạm ngưng')], max_length=100)),
                ('datetime_change', models.DateTimeField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
