# Generated by Django 3.1.3 on 2020-12-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201220_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(choices=[('1', 'Đang chuẩn bị'), ('2', 'Đang vận chuyển'), ('3', 'Đã giao'), ('4', 'Tạm ngưng')], default=1, max_length=100),
        ),
    ]
