# Generated by Django 3.1.3 on 2020-12-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20201220_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='status',
        ),
    ]
